### ISSUE TITLE
Repo dead?

### ISSUE THREAD

**Issue by enrichit** [danielstocks/react-sortable#16]
Haven't seen any activity here in a while, are you accepting pull requests?

**Comment by aaronshaf** [comment]
@danielstocks, perhaps you could add another collaborator?

**Comment by danielstocks** [comment]
Yeah sorry I've been swamped with work lately. @aaronshaf Let me know if you're interested, we could have a discussion. Send me an email at daniel@webcloud.se

**Comment by enrichit** [comment]
@danielstocks I would also be willing to help if need be.

**Comment by Dharmoslap** [comment]
It's pity there haven't been any updates and fixes for long time. Especially support of IE11 seems to be critical to me.

**Comment by Dharmoslap** [comment]
I'm interested in maintaining this repo instead of letting it die.

**Comment by danielstocks** [comment]
@Dharmoslap I've had plans of reviving it. Things to do is to make it up to date with the latest react best practices, and also as you mentioned IE11 support. I'd happily add you as a maintainer, or if you prefer to do pull requests.

**Comment by Dharmoslap** [comment]
Lovely, today it is exactly 2 years since your first commit.
I would appreciate to become a maintainer of this repo. 
We can start working on these steps:

1. review opened pull requests and merge them to master
2. go through all opened issue and try to resolve it
3. move from bower to npm
4. review the commits made by others, that didn't end up in PR and ask contributors to make PR, if it makes sense ([react-sortable/network](https://github.com/danielstocks/react-sortable/network), https://github.com/klaseskilson/react-sortable/commit/8f684b2526aa87c1c8de653f25271416da04ae40, https://github.com/KentaKomai/react-sortable/commit/1c3b116c98b53c1637d7786f44487c7fbb7caaa9, https://github.com/KentaKomai/react-sortable/commit/9aa38fb6e6b0b5bfca7707a411461d41e3c744a3)
5. update code for latest react v0.14.x, create a separate branch for react v15.0
6. update documentation
7. make a first release, add changelog.md to the repo

I'll try to invest as much time as I can to get it done soon.

For the future I would consider to rewrite the mixin into higher order component, because mixins 
will be deprecated soon and HOC seems to be more convenient pattern.

https://gist.github.com/sebmarkbage/ef0bf1f338a7182b6775
https://medium.com/@dan_abramov/mixins-are-dead-long-live-higher-order-components-94a0d2f9e750

Utilizing ES6 and ES7 should be considered too.

Another thing is that the release will need to be published to NPM as well.
You can do it yourself, or you can add me there too "npm owner add ladislavmaxa01".

**Comment by danielstocks** [comment]
@Dharmoslap Sounds like you have a plan! I added you as repo contributor.

> 1. review opened pull requests and merge them to master

Yes. I'm not sure if #8 is relevant anymore. But either merge or close.

> 2. go through all opened issue and try to resolve it

Yes, most of them should be quick fixes. Some are more complex like #15 and might require additional discussion.

> 3. move from bower to npm
Yes please :)

> 4. review the commits made by others, that didn't end up in PR and ask contributors to make PR, if it makes sense (react-sortable/network, klaseskilson@8f684b2, KentaKomai@1c3b116, KentaKomai@9aa38fb)

Nice. Yes please do we applicable.

> 5. update code for latest react v0.14.x, create a separate branch for react v15.0

Yes, lets start with 0.14.x. Fixing all the demos etc.

> 6 . update documentation
> 7. make a first release, add changelog.md to the repo

All good, you could start a new release branch or something, and branch out of that to start working on different stuff, and just ping me if you have any questions or need help in any specific regard.

I'll close this issue for now and consider this repo returned from the dead :)
