### ISSUE TITLE
this.isDragging not a function

### ISSUE THREAD

**Issue by sriprabha** [danielstocks/react-sortable#18]
I am trying to reuse one of the examples in the repo here, and I get an error over here: https://github.com/danielstocks/react-sortable/blob/master/demo/gridlist/SortableListItem.js#L6 
Am I missing something? Should I be including the path to Sortable.js in my example? Or just require('react-sortable') ?

**Comment by nickeljew** [comment]
Because inside src/Sortable.js, there is not export defined. If you using import or require directive to import Sortable object, the importer could not get any export object. The author of this project only offers only one kind of packing logic that you have to include the codes into your file by bower. The project do not support commonjs or requirejs mechanism.

**Comment by Dharmoslap** [comment]
fixed in https://github.com/danielstocks/react-sortable/commit/0549012d18dc1417562ff7fab39553ca5cd60f80
