### ISSUE TITLE
Sortable component mutates items array when dragging

### ISSUE THREAD

**Issue by ahutchings** [danielstocks/react-sortable#40]
When swapping the position of items in the array, the swapArrayElements function mutates the items array reference that is passed in via props. Before doing so, it should shallow clone the array to avoid mutating a prop.

cc @ryanswanson

**Comment by Dharmoslap** [comment]
Thanks for pointing this out, I'm considering this change. Could you please tell a bit more about what would be the advantage of having the array immutable in this case?

**Comment by ahutchings** [comment]
The React team generally recommends that props be considered immutable - https://facebook.github.io/react/docs/tutorial.html#reactive-state.

This is important because immutable props allows for useful comparisons to be done between previousProps and nextProps in react lifecycle methods such as shouldComponentUpdate, componentWillUpdate, and componentDidUpdate.

Also, by mutating items, the items prop reference does change when sorting, preventing optimization of sortable components with utilities like [shallowCompare](https://facebook.github.io/react/docs/shallow-compare.html).

I think we can resolve this issue by having swapArrayElements shallow copy items with `items.slice(0)` before setting new values.

**Comment by Dharmoslap** [comment]
I understand this, but still can't see any real gains by making the array immutable.
Since swapArrayElements() always return a different order of items array, the component needs to be re-render anytime swapArrayElements() is called. We could make it immutable for sure, but right now I cannot see how would the manual implementation of shouldComponentUpdate() bring some optimisation. If you have any ideas about the architecture of this component, you are more then welcome to create PR.
